export function getPizzaName() {
  const pizzas = [
    "Margherita",
    "Marinara",
    "Quattro Stagioni",
    "Carbonara",
    "Frutti di Mare",
    "Quattro Formaggi",
    "Crudo",
    "Napoletana",
    "Pugliese",
    "Montanara",
    "Emiliana",
    "Romana",
    "Fattoria",
    "Schiacciata",
    "Prosciutto",
    "Americana",
    "Tonno",
    "Valtellina",
    "Gorgonzola",
    "Calzone",
    "Pizza al Pesto",
    "Mediterranea",
    "Ortolana",
    "Diavola",
    "Rustica",
    "Contadina",
    "Parmigiana",
    "Capricciosa",
    "Ricotta e Spinaci",
    "Mare e Monti",
    "Padana",
    "Tedesca",
    "Tirolese",
    "Boscaiola",
    "Campagnola",
    "Vegetariana",
    "Bufalina",
    "Fontana",
    "Francescana",
    "Tartufata",
    "Tricolore",
    "Valdostana",
    "Caprese",
    "Fiori di zucca",
    "Bismarck",
    "Funghi",
    "Mimosa"
  ];

  return `${pizzas[Math.floor(Math.random() * pizzas.length)]}-${Math.floor(
    Math.random() * 100
  )}`;
}
